_BASE_: "../BASE-RCNN-RFPN-CBP20-DS25.yaml"
MODEL:
  META_ARCHITECTURE: "PanopticFPN"
  MASK_ON: True
  SEM_SEG_HEAD:
    LOSS_WEIGHT: 0.5
DATASETS:
  TRAIN: ("coco_2017_train_panoptic_separated_reduce_25",)
  TEST: ("coco_2017_val_panoptic_separated",)
