# _BASE_: "Base-Panoptic-FPN.yaml"
_BASE_: "Base-Panoptic-FPN-GNBNLow-CBP10.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "outputs/debug"
