_BASE_: "Base-Panoptic-FPN-GNBNLow-LESSSP-CBP10_50_1x.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
# SOLVER:
  # PRETRAINED_LR_SCALE: 0.1
  # ADDED_WEIGHT_KEYS:
  #   - 'horizontal'
  #   - 'topdown'
  # OPTIM: "adam"
  # WEIGHT_DECAY: 1e-4
OUTPUT_DIR: "outputs/FPN_GNBNLow_LESSSP-CBP10"

