_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  FPN:
    NORM: ""
SOLVER:
  STEPS: (168000, 200000)
  MAX_ITER: 216000
TEST:
  EVAL_PERIOD: 0
OUTPUT_DIR: "outputs/pretrained_baseline_nogn"
