_BASE_: "Base-Panoptic-RFPN-101-Baseline-DS1.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
# SOLVER:
  # PRETRAINED_LR_SCALE: 0.1
  # ADDED_WEIGHT_KEYS:
  #   - 'horizontal'
  #   - 'topdown'
  # OPTIM: "adam"
  # WEIGHT_DECAY: 1e-4
OUTPUT_DIR: "outputs/RFPN_101_baseline_ds1"

